### ISSUE TITLE
Unit Tests for DruidClient needed

### ISSUE THREAD

**Issue by kvsurii** [zapr-oss/druidry#38]
Hey!
Firstly, thanks for open sourcing this. Found this really helpful! 
Is there any way you could add Unit Tests for https://github.com/zapr-oss/druidry/blob/master/src/main/java/in/zapr/druid/druidry/client/DruidJerseyClient.java#L107

I am trying to figure out how to distinguish query results between select, timeseries and groupBy. I want the response to be as a List and not a String.

**Comment by GG-Zapr** [comment]
Hi @kvsurii,

We are glad that you have found this useful.

1. Regarding unit test cases, since most of the scenarios are related to connection creation and handling, we cannot unit test them. However, we will try to add some flow related test cases to it.

2. Having said that, although it is tested and is in use, if you encounter any issue, please raise an issue in the issues section or if you can provide a patch, we will be glad to accept it. We will resolve any issue raised as soon as possible.

3.  For List, we have a function
`<T> List<T> query(DruidQuery druidQuery, Class<T> className) throws QueryException;`
Let us know if this serves your purpose when you want list.

Let me know how can we help more.

**Comment by kvsurii** [comment]
Thanks for the comment, 
Sorry, I may not been have been more precise. Have the following questions - 
1. `<T> List<T> query(DruidQuery druidQuery, Class<T> className) throws QueryException;` --> What is class name in this case? 
2. Timeseries has the following result - 
```
[
    {
        "timestamp": "2018-08-10T00:00:00.000Z",
        "result": {
            "count": 0
        }
    }
]
```

Group By gives the following result - 
```
{
        "version": "v1",
        "timestamp": "2018-08-01T00:00:00.000Z",
        "event": {
            "result": 6
        }
}
```

How do you go about distinguishing the results? The official apache druid repo has Results based on each queryType. (Ex - https://github.com/apache/incubator-druid/blob/master/processing/src/main/java/io/druid/query/timeseries/TimeseriesResultValue.java)

**Comment by GG-Zapr** [comment]
Hi,

1. Example for list:
`List<DruidResponse> responses = client.query(query, DruidResponse.class);`

For the first result, it can be 
`class DruidResult {
    public int count;
}`

`class DruidResponse{
    public String timestamp;
    public DruidResult result;
}`
